Etutor/Models/Assign.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Etutor.Models
{
    public class Assign
    {
        [ForeignKey("Student")]
        public int Id { get; set; }
        public virtual Student Student { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual Staff Staff { get; set; }
        public ICollection<Document> Document { get; set; }
        public ICollection<Record> Record { get; set; }
        public ICollection<Message> Message { get; set; }


    }
}

Etutor/Controllers/AssignController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Etutor.DAL;
using Etutor.Models;
using EASendMail;

namespace Etutor.Controllers
{
    [Authorize]
    public class AssignController : Controller
    {
        private EtutorContext db = new EtutorContext();

        // GET: Assigns
        public ActionResult Index()
        {
            var assigns = db.Assigns.Include(a => a.Student);
            return View(assigns.ToList());
        }

        // GET: Assigns/CreateMultiple
        public ActionResult CreateMultiple()
        {
            ViewBag.Tutors = db.Tutors.ToList();
            ViewBag.Staff = db.Staffs.ToList();
            ViewBag.Students = db.Students.ToList();
            return View();
        }

        // POST: Assigns/CreateMultiple
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMultiple([Bind(Include = "Id")] List<int> stdID, int tutorID, int? staffID)
        {
            for (int i = 0; i < stdID.Count; i++)
            {
                Assign assign = new Assign();
                if (ModelState.IsValid)
                {
                    int index = stdID[i];
                    var student = db.Students.Where(m => m.Id == index).SingleOrDefault();
                    var tutor = db.Tutors.Where(m => m.Id == tutorID).SingleOrDefault();
                    var staff = db.Staffs.Where(m => m.Id == staffID).SingleOrDefault();
                    assign.Id = student.Id;
                    assign.Student = student;
                    assign.Tutor = tutor;
                    assign.Staff = staff;
                    db.Assigns.Add(assign);
                    db.SaveChanges();
                    Email(student.Email, tutor.Email, "Assign Notification", "You are assigned to new course");
                }
            }
            return RedirectToAction("Index");
        }

        // GET: Assigns/Edit/id
        public ActionResult Edit(int? id)
        {
            Assign assign = db.Assigns.Find(id);
            if (assign == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id = db.Tutors.ToList();
            return View(assign);
        }

        // POST: Assigns/Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id")] int? stdID, int tutorID, int? staffID)
        {
            Assign assign = db.Assigns.Where(m => m.Id == stdID).SingleOrDefault();
            if (ModelState.IsValid)
            {
                var student = db.Students.Where(m => m.Id == stdID).SingleOrDefault();
                var tutor = db.Tutors.Where(m => m.Id == tutorID).SingleOrDefault();
                var staff = db.Staffs.Where(m => m.Id == tutorID).SingleOrDefault();
                assign.Id = student.Id;
                assign.Student = student;
                assign.Tutor = tutor;
                assign.Staff = staff;
                db.SaveChanges();
                Email(student.Email, tutor.Email, "Change Tutor", "There is an update of tutor");
                return RedirectToAction("Index");
            }
            ViewBag.Id = new SelectList(db.Students, "Name", "Phone", "Email", assign.Id);
            return View(assign);
        }

        // GET: Assigns/Delete/id
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assign assign = db.Assigns.Find(id);
            if (assign == null)
            {
                return HttpNotFound();
            }
            return View(assign);
        }

        // POST: Assigns/Delete/id
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            Assign assign = db.Assigns.Find(id);
            var docList = db.Documents.Where(m => m.Assign.Id == id).ToList();
            var mesList = db.Messages.Where(m => m.Assign.Id == id).ToList();
            foreach (var doc in docList)
            {
                DeleteDoc(doc.Id);
            }
            foreach (var mes in mesList)
            {
                DeleteMes(mes.Id);
            }
            db.Assigns.Remove(assign);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public void DeleteDoc(int id)
        {
            var doc = db.Documents.Where(m => m.Id == id).FirstOrDefault();
            db.Documents.Remove(doc);
            db.SaveChanges();
        }

        public void DeleteMes(int id)
        {
            var mes = db.Messages.Where(m => m.Id == id).FirstOrDefault();
            db.Messages.Remove(mes);
            db.SaveChanges();
        }

        public void Email(string To, string Cc, string Subject, string TextBody)
        {
            try
            {
                SmtpMail oMail = new SmtpMail("TryIt");

                // Your gmail email address
                oMail.From = "etutorlearning99@gmail.com";

                // Set recipient email address
                oMail.To = To;
                oMail.Cc = Cc;

                // Set email subject
                oMail.Subject = Subject;

                // Set email bodytio
                oMail.TextBody = TextBody;

                // Gmail SMTP server address
                SmtpServer oServer = new SmtpServer("smtp.gmail.com");

                // Gmail user authentication
                // For example: your email is "gmailid@gmail.com", then the user should be the same
                oServer.User = "etutorlearning99@gmail.com";
                oServer.Password = "P@ssw0rd99";

                // If you want to use direct SSL 465 port,
                // please add this line, otherwise TLS will be used.
                // oServer.Port = 465;

                // set 587 TLS port;
                oServer.Port = 587;

                // detect SSL/TLS automatically
                oServer.ConnectType = SmtpConnectType.ConnectSSLAuto;

                Console.WriteLine("start to send email over SSL ...");

                EASendMail.SmtpClient oSmtp = new EASendMail.SmtpClient();
                oSmtp.SendMail(oServer, oMail);

                Console.WriteLine("email was sent successfully!");
            }
            catch (Exception ep)
            {
                Console.WriteLine("failed to send email with the following error:");
                Console.WriteLine(ep.Message);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Etutor/Views/Assign/CreateMultiple.cshtml
@using Etutor.Models
@using System.Data.Entity

@{ ViewBag.Title = "Create"; }
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Collapsible sidebar using Bootstrap 4</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="~/Content/css/dashboard.css">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

</head>

<body>
    <div class="wrapper">

        <!-- Sidebar -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <a href="/Index/Dashboard"><img alt='logo' style="width:70%; height: 70%;" src='~/Content/asset/logo.png'></a>
            </div>

            <ul class="list-unstyled components">
                <li>
                    @Html.ActionLink("Home", "Index", "Assign")

                </li>
            </ul>
            <ul class="list-unstyled CTAs">
            </ul>

        </nav>

        <!-- Page Content -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info 	.d-xl-none">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>

                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active m-2">
                                <div class="dropdown">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-cog" aria-hidden="true"></i>
                                    </button>
                                    <div class="dropdown-menu animate slideIn">
                                        <a class="dropdown-item" href="#">Link 1</a>
                                        <a class="dropdown-item" href="#">Link 2</a>
                                        <a class="dropdown-item" href="#">Link 3</a>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item active m-2">
                                <div class="dropdown">
                                    @Html.ActionLink("Log out", "LogOut", "Home", new { area = "" }, new { @class = "btn btn-primary" })

                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

            </nav>
            <div class="d-block m-3  content-header">
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
                <h3>Assign</h3>
            </div>
            <form action="/Assign/CreateMultiple" method="post">
                @Html.AntiForgeryToken()

                <div class="form">
                    <div class="row d-flex justify-content-center">
                        <div class="col-auto my-1 select-input">
                            <label class="mr-sm-2" for="inlineFormCustomSelect">Tutors</label>
                            <select name="tutorID" class="custom-select mr-sm-2" @*id="inlineFormCustomSelect"*@>
                                @foreach (var item in ViewBag.Tutors)
                                {
                    <option value="@item.Id">@item.Name</option>}
                            </select>
                        </div>
                        <div class="col-auto my-1 select-input">
                            <label class="mr-sm-2 d-block" for="inlineFormCustomSelect">Students</label>
                            @foreach (var item in ViewBag.Students)
                            {
                <div class="d-block">
                    <input type="checkbox" name="stdID" value="@item.Id">
                    <label>@item.Name</label>
                </div>}
                        </div>
                    </div>
                    <div class="row d-flex justify-content-center mt-4">
                        <button class="btn btn-primary" type="submit" value="Assign"><i class="fa fa-plus" aria-hidden="true"></i>Assign</button>
                        @*<input type="submit" value="Assign" class="btn btn-default" />*@

                    </div>

                </div>
            </form>
        </div>

    </div>


    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
</body>

</html>

Etutor/Views/Assign/Delete.cshtml
@model Etutor.Models.Assign

@{ ViewBag.Title = "Delete"; }

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Collapsible sidebar using Bootstrap 4</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="~/Content/css/dashboard.css">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

</head>

<body>
    <div class="wrapper">

        <!-- Sidebar -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <a href="/Index/Dashboard"><img alt='logo' style="width:70%; height: 70%;" src='~/Content/asset/logo.png'></a>
            </div>

            <ul class="list-unstyled components">
                <li>
                    @Html.ActionLink("Home", "Index", "Assign")

                </li>
            </ul>
            <ul class="list-unstyled CTAs">
            </ul>

        </nav>

        <!-- Page Content -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info 	.d-xl-none">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>

                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active m-2">
                                <div class="dropdown">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-cog" aria-hidden="true"></i>
                                    </button>
                                    <div class="dropdown-menu animate slideIn">
                                        <a class="dropdown-item" href="#">Link 1</a>
                                        <a class="dropdown-item" href="#">Link 2</a>
                                        <a class="dropdown-item" href="#">Link 3</a>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item active m-2">
                                <div class="dropdown">
                                    @Html.ActionLink("Log out", "LogOut", "Home", new { area = "" }, new { @class = "btn btn-primary" })

                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

            </nav>

            <div class="row d-flex justify-content-center">
                <h3>All documents related to this assign will be deleted !!!</h3>
            </div>

            <div class="row d-flex justify-content-center">
                <div class="col-auto my-1 select-input">
                    <label class="mr-sm-2" for="inlineFormCustomSelect">Student</label>
                </div>
                <div class="col-auto my-1 select-input">
                    @Html.DisplayFor(model => model.Student.Name)
                </div>

            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-auto my-1 select-input">
                    <label class="mr-sm-2 d-block" for="inlineFormCustomSelect">Tutor</label>
                </div>
                <div class="col-auto my-1 select-input">
                    @Html.DisplayFor(model => model.Tutor.Name)
                </div>

            </div>

            <div class="row d-flex justify-content-center">
                @using (Html.BeginForm())
                {
    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>}
            </div>

        </div>

    </div>


    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
</body>

Etutor/Views/Assign/Edit.cshtml
@using Etutor.Models
@using System.Data.Entity
@model Assign

@{ ViewBag.Title = "Edit"; }
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Collapsible sidebar using Bootstrap 4</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="~/Content/css/dashboard.css">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

</head>

<body>
    <div class="wrapper">

        <!-- Sidebar -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <a href="/Index/Dashboard"><img alt='logo' style="width:70%; height: 70%;" src='~/Content/asset/logo.png'></a>
            </div>

            <ul class="list-unstyled components">
                <li>
                    @Html.ActionLink("Home", "Index", "Assign")

                </li>
            </ul>
            <ul class="list-unstyled CTAs">
            </ul>

        </nav>

        <!-- Page Content -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info 	.d-xl-none">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>

                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active m-2">
                                <div class="dropdown">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-cog" aria-hidden="true"></i>
                                    </button>
                                    <div class="dropdown-menu animate slideIn">
                                        <a class="dropdown-item" href="#">Link 1</a>
                                        <a class="dropdown-item" href="#">Link 2</a>
                                        <a class="dropdown-item" href="#">Link 3</a>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item active m-2">
                                <div class="dropdown">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-user" aria-hidden="true"></i>
                                    </button>
                                    <div class="dropdown-menu animate slideIn">
                                        <a class="dropdown-item" href="#">Link 1</a>
                                        <a class="dropdown-item" href="#">Link 2</a>
                                        <a class="dropdown-item" href="#">Link 3</a>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item active m-2">
                                <div class="dropdown">
                                    @Html.ActionLink("Log out", "LogOut", "Home", new { area = "" }, new { @class = "btn btn-primary" })

                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

            </nav>
            <div class="d-block m-3 content-header">
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
                <h3>Change Tutor</h3>
            </div>
            <form action="/Assign/Edit" method="post">
                @Html.AntiForgeryToken()

                <div class="form">
                    <div class="row d-flex justify-content-center">
                        <div class="col-auto my-1 select-input">
                            <label class="mr-sm-2" for="inlineFormCustomSelect">Student</label>
                            <select name="stdID" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                                <option value="@Model.Id" selected>@Model.Student.Name </option>
                            </select>
                        </div>
                        <div class="col-auto my-1 select-input">
                            <label class="mr-sm-2 d-block" for="inlineFormCustomSelect">Tutor</label>
                            <select name="tutorID" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                                @foreach (var item in ViewBag.Id)
                                {
                    <option value="@item.Id">@item.Name</option>}
                            </select>
                        </div>
                    </div>
                    <div class="row d-flex justify-content-center mt-4">
                        <button class="btn btn-primary" type="submit" value="Update"><i class="fa fa-edit" aria-hidden="true"></i>Change Tutor</button>
                    </div>

                </div>
            </form>
        </div>

    </div>


    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
</body>

</html>